### ISSUE TITLE
Adding default styles from Font Awesome

### ISSUE THREAD

**Issue by HugoGiraudel** [TimPietrusky/weloveiconfonts#23]
Font Awesome uses a lot of default styles WeLoveIconFonts removed. Please have a look here, line 32 to 75: https://github.com/FortAwesome/Font-Awesome/blob/master/css/font-awesome.css

Currently, it is impossible to port a project from Font Awesome to WeLoveIconFonts because of these styles missing. 

Any chance you'd put them back or give an option to have them?

Thanks a lot.

**Comment by FinalDes** [comment]
Font Awesome is outdated
