### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by Raineo** [TimPietrusky/weloveiconfonts#42]
Love your tool, thank you very much for creating this.

Do you plan to implement requests over https protocol at some point in the future?
Currently, when our users access our website through https and it starts downloading resources over http, the browser throws a warning, indicating that some items are downloaded over an unsecured connection. I know it's a matter of perception but it can be a bit confusing to the user and lowers their trust level in using the web page they are on.
The workaround is currently to download the css and the font files to the local server to access them through a secure connection.

I understand that this might be very low on the priority list, as it requires monetary expenses in addition to time. Have you thought about setting up a 'Donate' link? It could help cover the cost of security certificates. People who value your work and want to support your project will help out. I know I would.

**Comment by luisrudge** [comment]
:+1:  for ssl

**Comment by luisrudge** [comment]
in the mean time, I'm using this: https://cdnjs.com/libraries/zocial

**Comment by dervondenbergen** [comment]
Wouldn't it be easy, by simply using the free [cloudflare](https://www.cloudflare.com/plans) plan in this case? Setting it up takes like 10 minutes max and doesn't require changes on the server.

**Comment by designrDevelopr** [comment]
+1 for SSL.
Maybe try letsencrypt.org?

**Comment by markhillard** [comment]
+1 for SSL. Icons don't display on CodePen pens if you're on their site via https.

**Comment by applecrusher** [comment]
+1 for SSL

**Comment by heyallan** [comment]
The whole WLIF website can be hosted on github pages, and use any static generator instead of PHP, then connect files to any free CDN like: https://cdnjs.com, or https://rawgit.com. All for free.

Unless you really need PHP.

**Comment by harishankards** [comment]
Hey guys, did you all find any way to use the icon fonts in `https` way?
I'm struggling with `http` as my app throws an error.

**Comment by haukebruno** [comment]
+1, we are on it, so stay tuned please :)

**Comment by alloyking** [comment]
Still no https guys?  Can I help?

**Comment by mkows** [comment]
Same here +1. @haukebruno, is there any update on SSL support?

**Comment by TimPietrusky** [comment]
Together with @haukebruno WLIF is now migrated to https!
