### ISSUE TITLE
https for zocial, please? 

### ISSUE THREAD

**Issue by mashablair** [TimPietrusky/weloveiconfonts#68]
Hi Tim!  I just pushed my project on GitHub and all my zocial icons disappeared because I was using the http link (like this `<link rel="stylesheet" href="http://weloveiconfonts.com/api/?family=zocial">`) and not the https.  Could you please provide the way to fix that?  GitHub suggested to contact you.  Thanks!!

**Comment by paulwired** [comment]
@mashablair Also having this problem. Looks like all they need to do is install an SSL certificate.

**Comment by piousminion** [comment]
I'm having the same problem with Entypo.  As my site is secure only, no non-SSL content will load.

SSL is easy and even FREE these days. Check out EFF's certbot, or if less technically inclined, https://www.sslforfree.com/

**Comment by gtlt** [comment]
Same here. May I suggest https://letsencrypt.org ?

**Comment by jchaplin2** [comment]
Hi,

Did anyone get www.sslforfree.com to work?? I downloaded the file and uploaded to my github pages website and I couldn't view it (404 error).

**Comment by b12f** [comment]
I really need this to get fixed or I'll have to switch to another font cdn.

**Comment by GlobalOutsourcing** [comment]
Please, please add an SSL the site: http://weloveiconfonts.com/api/?fam (They are free!)

Causing issues on our sites.

Thanks.

**Comment by haukebruno** [comment]
As mentioned in #42 we are on it. Please stay tuned :)

**Comment by motatoes** [comment]
Is there any update on this issue? Anyway we can help? Chrome is blocking mixed content when http is being served from an https site, so its not possible to load the font

**Comment by NikhilSharmay** [comment]
Host! Can you please make this over https :100:  
Try sslforfree / letsencrypt

**Comment by b12f** [comment]
The last update to this repo was five years ago. I'm going to take a guess and this will not be implemented. I'll be switching to self-hosting or using a different font.

**Comment by haukebruno** [comment]
> Host! Can you please make this over https 
> Try sslforfree / letsencrypt

@NikhilSharmay we set up a dev system last sunday and perform some internal tests right now. Afterwards we'll switch wlif to a new system with HTTPS, HTTP2 and all that stuff.

**Comment by haukebruno** [comment]
#42 resolves this :)
