### ISSUE TITLE
Symbols not showing up

### ISSUE THREAD

**Issue by Immanuel1337** [TimPietrusky/weloveiconfonts#70]
heey yo, i`m currently starting off with HTML and CSS in during my internship and i`m having trouble with the most of the icon fonts featured on your website. even though i did everything right with the sourcing (obviously, it works with other symbols) it often doesnt show the symbol i`m trying to make appear which makes me unable to use them and have to find a different way to accomplish my task. i was wondering if you have any tips or if those fonts are just bugged at some point or maybe i`m doing something wrong. a reply would be very appreciated.

**Comment by Immanuel1337** [comment]
**HTML:**
`<div class="menubutton"><span class="typcons-grid"></span></div>`

**CSS:**
`@import url(http://weloveiconfonts.com/api/?family=typicons);
[class*="typicons-"]:before {
  font-family: 'Typicons', sans-serif;
}

.menubutton {
  color: #FFFFFF;
  text-size: 20px;
  text-align: center;
}`

thats the part i`m talking about (just an example, tried it with other symbols in other sections etc.)

**Comment by Immanuel1337** [comment]
> Put your code online somewhere so we can see?

**Comment by Immanuel1337** [comment]
whoops i`m new to github :'D

**Comment by FlashBuddy** [comment]
Works for me. Here is my code:

`	<style type="text/css">
	@import url(http://weloveiconfonts.com/api/?family=typicons);
	[class*="typicons-"]:before {
	  font-family: 'typicons', sans-serif;
	}
	.menubutton {
		color: #FFFFFF;
		font-size: 20px;
		text-align: center;
		background-color: tomato;
		padding: 10px 35px 4px;
		width: 125px;
	}
	</style>
	<div class="menubutton"><span class="typicons-grid"></span></div>`

Do you have a typo?

**Comment by Immanuel1337** [comment]
man no idea why but if i paste this into my html it works for me too.
i`m going to continue with that on that way then, i guess.

anyways, thank you very much!!

**Comment by mkows** [comment]
Hi @Immanuel1337 , could you please mark this issue as closed?
