### ISSUE TITLE
ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by Zdeno5** [TimPietrusky/weloveiconfonts#72]
Page is not working, cert expired

**Comment by TimPietrusky** [comment]
@Zdeno5 sorry for this problem, we are not sure why, but the monitoring didn't warn us about it. @haukebruno is on it so it will not happen again.

**Comment by Zdeno5** [comment]
again ERR_CERT_DATE_INVALID

**Comment by haukebruno** [comment]
@Zdeno5 yep sorry for this issue again. In the next tech refresh we'll fully automate the cert renewal.

The cert was renewed just a few minutes ago
