### ISSUE TITLE
SSL Certificate expired

### ISSUE THREAD

**Issue by Krandelbord** [TimPietrusky/weloveiconfonts#75]
Hello,
Ceritifcate for https://weloveiconfonts.com/ is expired sine 2023-09-04.
It is not possible to open page in chrome/chromium 
![image](https://github.com/TimPietrusky/weloveiconfonts/assets/8105637/44c24934-90b9-4fc3-a93f-405f618df10a)

**Comment by haukebruno** [comment]
Fixed. We had an issue while automatically reloading the SSL proxy which has been mitigated now.
